---
project : coFF-oFF-project-1-D
program : train_model.py
parameters : 
  batch_size: 512
  bidirectional: True
  dense_units: 256
  dropout_rate: 0.1
  epochs : 20000
  learning_rate: 0.0001
  lstm_dropout_rate: 0
  lstm_units: 4
  min_delta: 0
  optimizer: adam
  patience: 100
  reg: none
  reg_coeff: 0
  soc_activation_out: sigmoid
