---
project : coFF-oREC-project
program : train_model.py
method : random
metric : 
  goal : minimize
  name : val_loss
parameters :
  #### META LEARNING HYPERPARAMS ####
  epochs : 
    value : 20000
  optimizer : 
    value : adam
  min_delta : 
    value : 0
  patience : 
    value : 100
  batch_size:
    values:
      - 512
      - 1024
      - 2048
  learning_rate:
    values:
      - 0.00001
      - 0.0001
      - 0.0005
      - 0.001

  #### NETWORK ARCHITECTURE HYERPARAMS ####
  soc_activation_out : 
    value : sigmoid
  dense_multiple : 
    values : 
      - 4
      - 8
      - 16
  lstm_units:
    values:
      - 4
      - 8
      - 16
  bidirectional :
    values : 
      - True
      - False

  #### REGULARIZATION HYERPARAMS ####
  lstm_dropout_rate : 
    value : 0
  reg : 
    values :
      - l1
      - l2
      - none
  reg_coeff :
    values : 
      - 0.000001
      - 0.00001
  dropout_rate :
    values :
      - 0.0
      - 0.1
      - 0.2
      - 0.4